export const WOW_CLASSES = [
	{ name: 'death knight', color: '#C41E3A' },
	{ name: 'demon hunter', color: '#A330C9' },
	{ name: 'druid', color: '#FF7C0A' },
	{ name: 'evoker', color: '#33937F' },
	{ name: 'hunter', color: '#AAD372' },
	{ name: 'mage', color: '#3FC7EB' },
	{ name: 'monk', color: '#00FF98' },
	{ name: 'paladin', color: '#F48CBA' },
	{ name: 'priest', color: '#FFFFFF' },
	{ name: 'rogue', color: '#FFF468' },
	{ name: 'shaman', color: '#0070DD' },
	{ name: 'warlock', color: '#8788EE' },
	{ name: 'warrior', color: '#C69B6D' },
];
